name: testShop
version: '${project.version}'
main: a.testshop.TestShop
api-version: 1.19
commands:
  testshop:
    description: testShop
    usage: /<command> [create,reload] [stone]
    aliases: [shop]